### ISSUE TITLE
What should the language prompt in Rookie be?

### ISSUE THREAD

**Issue by AbeHandler** [AbeHandler/rookie#101]
@myersnews  1.27.16  you have something that says “subjects related to mitch landrieu” and then “found 243 stories for mitch landrieu related to:” — what is the difference between them? they’re all stories. you should choose consistent language. i would have to think about this more to know which language to use.

<img width="1078" alt="screen shot 2016-01-27 at 8 30 24 am" src="https://cloud.githubusercontent.com/assets/1252925/12614854/57a7adcc-c4d0-11e5-8b1b-931d3b498997.png">

**Comment by AbeHandler** [comment]
@myersnews @brendano on 1.27.16 Steve M. said (in email) that the two different bits of descriptive language in the Rookie UI  "subjects related to" (describing global facets) and "found X stories for ...." were confusing. I agree with him.

I agree w/ steve m. that there should be only one verbal description of what rookie is doing. I got rid of "subjects related to" because this can be rolled into the "found X stories for..." (which is called the 'status message' in the code, i.e. components/Status.jsx)

This opens a new design problem, seen in the pictures below

<img width="1236" alt="screen shot 2016-01-27 at 10 13 30 am" src="https://cloud.githubusercontent.com/assets/1252925/12617677/b74f4dda-c4de-11e5-9833-10bb801ca441.png">
<img width="1233" alt="screen shot 2016-01-27 at 10 13 40 am" src="https://cloud.githubusercontent.com/assets/1252925/12617678/b750b986-c4de-11e5-8343-c50b0db05a4f.png">

I think the answer is to this design problem is to make the "binned facets" (i.e. the facets for 2010 etc) look more like the global facets (i.e. the grey buttons) and to roll the global facet buttons into the status message. So the global status will read like an English sentence except parts of it will be the grey buttons you can click.

I am typing this all here because I think its really relevant to the core design problem of Rookie: how to make the linguistic facets make sense to the user.

One thing that is really interesting about this is that, if this design change works, then it would mean that, at least in this case, the easiest way of understanding what Rookie is doing is reading a sentence about what Rookie is doing -- not seeing a list of metadata or a list of buttons or a list of check marks or what have you. So natural language is a sort of interface for Rookie's conclusions. So like language is good for explaining stuff. Deeeep man.

**Comment by AbeHandler** [comment]
![this](https://cloud.githubusercontent.com/assets/1252925/12618970/29209414-c4e4-11e5-86c0-f7b6f2a2ddc3.png)

**Comment by myersnews** [comment]
I think that’s a good solution, to make the facets part of a sentence. it would be something like:
Found X stories for QUERY related to facet1, facet 2 and facet 3. 

You have to set it up to add an “and” at the end. Or you could just use the colon and pull the global facets up to the line above.
--
Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews

**Comment by AbeHandler** [comment]
![new status](https://cloud.githubusercontent.com/assets/1252925/12621869/98306eea-c4f0-11e5-9276-0acbe1dec3b0.png)

**Comment by AbeHandler** [comment]
new design sort of makes this less important. closing.
