### ISSUE TITLE
stronger visual cue for T selection in timeseries chart

### ISSUE THREAD

**Issue by brendano** [AbeHandler/rookie#107]
it is very faint right now.  the highlight visual cue is to give a slightly darker gray, and maybe to darken the area chart also?

then the highlight visual should be stronger somehow.  some possibilities include darker/bolder colors.  or, lighter bacgkround and stronger saturation in the area/line visual elements?  i guess it just has to be something more prominent, somehow.  i feel like it's easy to miss currently.

it could just be me though.

current design seems to be

(1) no T selection (or rather, T interval is the full timeline):
highlight entire timeline
(2) with T selection: highlight the T set interval

i'd propose

(1) no T selection: highlight nothing
(2) T selection: highlight the T set interval

this gives more latitude to make the highlight stronger, since it doesn't visually clutter or overwhelm in the (1) case.

**Comment by AbeHandler** [comment]
I think this is covered in new designs. @brendano : OK to close? 

<img width="1069" alt="screen shot 2016-02-15 at 11 42 42 pm" src="https://cloud.githubusercontent.com/assets/1252925/13067423/d69ff93c-d43d-11e5-837e-a929ebc9fda8.png">
