### ISSUE TITLE
replace c3 w/ react

### ISSUE THREAD

**Issue by AbeHandler** [AbeHandler/rookie#112]
Oh man. This will be painful but I think the time has come. Issues stemming from the mix of c3 + react...

https://github.com/AbeHandler/rookie/issues/110
https://github.com/AbeHandler/rookie/issues/111
https://github.com/AbeHandler/rookie/issues/109
https://github.com/AbeHandler/rookie/issues/106
https://github.com/AbeHandler/rookie/issues/90

**Comment by AbeHandler** [comment]
@brendano I think it's time. Like a bandaid, eh?

**Comment by brendano** [comment]
svg isnt that hard it will be good

**Comment by AbeHandler** [comment]
ok working now
