### ISSUE TITLE
example for subsentence summarization: sentence undersegmentation

### ISSUE THREAD

**Issue by brendano** [AbeHandler/rookie#114]
i guess this is only <=2 sentences according to the sentence segmenter.  if i'm understanding the summarizer correctly.  two possible solutions include

1. fix segmenter (hard?)
2. be defensive at summariation time to trim overly long sentences. e.g. +/- 20 word window (but no larger than nearest sentence boundaries) around the target term? (either Q or F).  eventually this leads to a fancier model but something simple might be enough to solve issues like this.

> By Matt Davis , The Lens staff writerThe committee established by Mayor Mitch Landrieu to advise him on issues regarding the citys jail complex meets today at 2 , less than a day after Sheriff Marlin Gusman blasted the groups work in a letter to the City Council.The Council is to consider Thursday a long-tabled ordinance that will let Gusman start building new jail cells . The ordinance was strongly guided by the work of the mayors working group on criminal justice.Gusman wrote that the ordinance granting him permission to build a 1,438-bed jail facility contains provisions that would be impossible for the Sheriffs Office to accomplish , and absolutely not in the best interest of our citizens.Chief among Gusmans complaints is a requirement that the new facility accommodate all types of inmates , from local pre-trial detainees to state convicts , and mental-health patients to federal immigration prisoners.The working group made that requirement so that it could call for Gusman to demolish all other jail facilities and shrink the jail complex capacity within the bounds recommended by a national expert.In his letter , Gusman also questioned a requirement that he use the Orleans Parish Prison only as a holding facility , not long-term housing , after the Federal Emergency Management Agency spent $ 24 million to upgrade it after Hurricane Katrina.Clearly , this stipulation demonstrates a fundamental lack of understanding and knowledge of the operations of the Sheriffs Office , Gusman wrote.The sheriff also wrote that a call for him to demolish 400 new temporary beds within 365 days of the 1,438-bed facility being completed is unrealistic and must be amended.Many of the other provisions are arbitrary , capricious , and beyond the responsibility and authority of the Orleans Parish Sheriffs Office to accomplish , Gusman wrote.Gusman only agreed to abide without condition to one of the 21 conditions of the ordinance , a minor clause regarding a right-of-way lease.Gusman called for the removal or amendment of several conditions , wrote that one could only be complied with if the city gives substantial additional funding , and only agreed to abide by several others to the extent possible.The City Council is scheduled to grant Gusman permission to build the 1,438-bed jail by voting on the ordinance on Feb. 3 ....

<img width="1280" alt="screen shot 2016-01-28 at 10 51 31 pm" src="https://cloud.githubusercontent.com/assets/1677/12666784/ca0e32c2-c611-11e5-90ce-64865cc25ef1.png">

**Comment by brendano** [comment]
is there some more general problem with sentences?  i'm noticing more cases where there is a period ending a sentence, but then there is no space after it before the first word of the next sentence.  is this a display problem or a deeper data structure / sentence seg problem?

<img width="1138" alt="screen shot 2016-01-28 at 10 59 19 pm" src="https://cloud.githubusercontent.com/assets/1677/12666877/c9ca6ab4-c612-11e5-983b-043b5c2063d0.png">
<img width="271" alt="screen shot 2016-01-28 at 10 58 50 pm" src="https://cloud.githubusercontent.com/assets/1677/12666878/c9cad1fc-c612-11e5-95cf-b57ae2a11b2e.png">

**Comment by myersnews** [comment]
I can look at the originals on the site to see. I think it happened as text
was processed for rookie.

Sent from my iPhone, which may explain typos & brevity. Possibly dictated
to Siri, which would account for gibberish.

On Jan 28, 2016, at 9:59 PM, brendano <notifications@github.com> wrote:

is there some more general problem with sentences? i'm noticing more cases
where there is a period ending a sentence, but then there is no space after
it before the first word of the next sentence. is this a display problem or
a deeper data structure / sentence seg problem?

[image: screen shot 2016-01-28 at 10 59 19 pm]
<https://cloud.githubusercontent.com/assets/1677/12666877/c9ca6ab4-c612-11e5-983b-043b5c2063d0.png>
[image: screen shot 2016-01-28 at 10 58 50 pm]
<https://cloud.githubusercontent.com/assets/1677/12666878/c9cad1fc-c612-11e5-95cf-b57ae2a11b2e.png>

—
Reply to this email directly or view it on GitHub
<https://github.com/AbeHandler/rookie/issues/114#issuecomment-176562183>.

**Comment by AbeHandler** [comment]
This is fixed for the Lens corpus. There was an error in preprocessing (replacing \n with ""). There seem to be issues on Gawker too. Keeping track of those on this thread: #161
