### ISSUE TITLE
got a funny layout thing for "N articles" on left

### ISSUE THREAD

**Issue by brendano** [AbeHandler/rookie#115]
this happens when facets are added to the list, then then cancelled and the counts go up to 2 digits.  the facetes on the list somehow contorts the layout constraints maybe.

<img width="501" alt="screen shot 2016-01-29 at 12 19 10 pm" src="https://cloud.githubusercontent.com/assets/1677/12682652/8d44ab7a-c682-11e5-8bba-40ac6e9e367b.png">

**Comment by brendano** [comment]
oh it's related to bin selection.

![screen shot 2016-01-29 at 12 25 06 pm](https://cloud.githubusercontent.com/assets/1677/12682781/5cc03cb6-c683-11e5-9746-6fcc156b02e8.png)
![screen shot 2016-01-29 at 12 25 04 pm](https://cloud.githubusercontent.com/assets/1677/12682782/5cc41890-c683-11e5-9fb7-19a938309678.png)

**Comment by AbeHandler** [comment]
no temporal facets for now... so this can be closed
