### ISSUE TITLE
unselect facet by clicking on it doesn't give visual cue at the facet

### ISSUE THREAD

**Issue by brendano** [AbeHandler/rookie#116]
hovering on a facet = red
facet is selected = red

move your mouse over a currently-selected facet.
click it to unselect it.
it stays red even though it's unselected.

other parts of the screen indicate the unselection happened, of course ... but i find my attention is focused on the facet since i moved my mouse to click on it.  so i get a little confused ... did my click work?

not sure on the solution if any.  i guess making the hover state have a different visual style than the facet selection state, would be a quick fix.  (they're just different css classes i'm guessing?)

**Comment by AbeHandler** [comment]
This one can be closed. It is fixed w/ new design, where facets have Xs on them.

![image](https://cloud.githubusercontent.com/assets/1252925/13067471/4c6c9d00-d43e-11e5-8336-cd803c0ca9b4.png)
