### ISSUE TITLE
idea: (x) click targets on description sentence to loosen constraints

### ISSUE THREAD

**Issue by brendano** [AbeHandler/rookie#117]
> Found 0 stories for mitch landrieu and Mayor Mitch Landrieus in Apr 2013

could put little (x) boxes on the F and T descriptions to give a clear mechanism how to cancel them.

> Found 0 stories for mitch landrieu and Mayor Mitch Landrieus (x) in Apr 2013 (x)

where  the (x) boxes could be a superscript or something.

i feel like i've seen this in tagging interfaces ... on facebook maybe? ... before ...

**Comment by AbeHandler** [comment]
<img width="1219" alt="screen shot 2016-02-04 at 5 16 50 pm" src="https://cloud.githubusercontent.com/assets/1252925/12831581/232d457c-cb63-11e5-9b40-7518096557ca.png">

I think this is a good idea/necessary feature. In the new slider-timeseries design, there should be a little X by the facet on zoom (above birth certificate in this case)

**Comment by brendano** [comment]
ooh what about an (x) above the Q too?  if you click it then the F gets promoted to the new Q!  e.g. you no longer care about donald trump and just want to see what's going on with birth certificate.  maybe this is the easy interface mechanism for F-to-Q promotion that's been eluding us.

**Comment by AbeHandler** [comment]
Good idea. So if you clicked the X over donald trump it would take you to...

<img width="1199" alt="screen shot 2016-02-04 at 5 53 16 pm" src="https://cloud.githubusercontent.com/assets/1252925/12832476/43daa382-cb68-11e5-9d0b-fc1597788278.png">

**Comment by brendano** [comment]
conspiracy semantics

hm, a few obvious facet errors that jump out
 - "birth certificates": FP since should have merged with the Q
 - "long-form birth": overly shortened relative to, i'm presuming, "long-form birth certificate"?  then that, debatably, is repetitive with the Q.  (not sure if merging or not is the right way to think about that)
 - "Image via AP": yep it's a noun phrase.  i guess you'd hope IDF scoring would get it.  maybe there's a way to specialcase out photo credits (related issue: dates like "last week", though that's more linguistic and less domain-specific).

**Comment by AbeHandler** [comment]
HTML trivia... http://www.w3schools.com/tags/tag_sup.asp

**Comment by myersnews** [comment]
Chiming in late as I’ve been lost in newborn land, but yeah, this could be cool. If you click the X for the query then the facet becomes the query and the app refreshes with the results. My only reservation here is that this is a big switch that would be activated by clicking one little X, and if you don’t have a “back” button or some equivalent, then it may piss off the user who didn’t realize it would change everything.
--
Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews
