### ISSUE TITLE
same aspect ratio on chart and sparklines

### ISSUE THREAD

**Issue by AbeHandler** [AbeHandler/rookie#123]
height/wight needs to be same for both

**Comment by AbeHandler** [comment]
Sort of an interesting design question here. The aspect ratio of chart & sparklines needs to be the same. As the w/h ratio gets bigger (wider and shorter) there is less room for sparklines. Dunno if this qualifies as a proper HCI question, but it is definitely a clearcut design tradeoff.

**Comment by brendano** [comment]
cleveland or tukey or someone definitely wrote papers about aspect ratios
and line graphs...



-- 
-brendan [mobile]
