### ISSUE TITLE
Do you need still temporal bins if you have time sliders on the chart?

### ISSUE THREAD

**Issue by AbeHandler** [AbeHandler/rookie#124]
One version of Rookie had "temporal facets". Now that the chart has sliders, I'm not sure if you want or need the temporal facets on the left. 

<img width="807" alt="screen shot 2016-02-02 at 7 14 39 pm" src="https://cloud.githubusercontent.com/assets/1252925/12768941/a1c1cd1e-c9e1-11e5-8d20-b88e914db6fd.png">
<img width="809" alt="screen shot 2016-02-02 at 7 15 20 pm" src="https://cloud.githubusercontent.com/assets/1252925/12768940/a1c1164e-c9e1-11e5-93cb-f23e9959d541.png">

**Comment by brendano** [comment]
oh boy.  i thought about this a while ago then came to like the temporal bins.  but i do agree it is getting repetitive.

**Comment by AbeHandler** [comment]
gah! the sliders are unexpectedly awesome. you can slide the black rectangle and, as you are sliding it, read the top stories/snippets off the doclist (which updates based on the date range in the slider). so like: move the left rectangle to the right & the top story in the doclist updates. this allows you to read the evolving relationship between q, f and t through time as you slide the rectangle.

**Comment by AbeHandler** [comment]
ok this relates to #126. This particular thread can be closed
