### ISSUE TITLE
snippet generation speedup

### ISSUE THREAD

**Issue by AbeHandler** [AbeHandler/rookie#128]
Snippet generation is a bottleneck for large document sets. For instance, Q=Donald Trump, F=Jay Leno, Corpus=Gawker takes 10 seconds in current app

**Comment by AbeHandler** [comment]
@brendano snippet generation is a new Rookie bottleneck. when there are ~800 documents for, say, Donald Trump and Leno -- the current snippet algorithm is pretty slow. 

Open FST? Cython? Indexing a subset of potentially relevant sentences?

**Comment by AbeHandler** [comment]
Discussed at 2/16/16 meeting. Step 1 find the bottle neck. Then two solutions on white board. The thing by whoosh is not super legible but says to read whoosh docs on "music tags" to figure out how to build your own index.

![img_20160216_100656_1](https://cloud.githubusercontent.com/assets/1252925/13096678/15136180-d4e9-11e5-8bc8-86e63e465145.jpg)

**Comment by brendano** [comment]
ah yeah sorry i dont know if it's "music tags" but the feature to support
indexing and navigation on tags, in general

**Comment by AbeHandler** [comment]
@brendano I was using joblib to cache the doclist making method, thinking this was clever. (Joblib allows you to cache methods with mutable output, by pylru does not). As it turns out, it was taking around 9 seconds to stash the output into joblib's cache. Just removing the decorator speeds things up from 10 seconds to about a second and a half (on ~1000 docs), which is definitely slow but also approaching acceptable.

When I was learning to program, I was taught: "don't reinvent the wheel." But I am starting to come around to your philosophy of trying to avoid dependencies when possible. This job lib bug cost ~5 hours.

**Comment by brendano** [comment]
blah.  i guess the metaphor breaks down when you are borrowing someone
else's 100k LOC wheel you don't understand with a thousand unanticipated
subtleties.  serialization and deserialization time a bottleneck, yeah
makes sense for sure.
