### ISSUE TITLE
enter key working again

### ISSUE THREAD

**Issue by brendano** [AbeHandler/rookie#152]
it always gets an error when i enter a query and press return. this seems to be because the corpus identifier seems to get lost.  do we have to always enter the query in the URL?

**Comment by AbeHandler** [comment]
Hrm. there is a js variable that gets pushed thru indicating corpus.

If I go to http://hobbes.cs.umass.edu/~ahandler/www/rookie/main.cgi/?q=Mitch%20Landrieu&corpus=lens

and type "taxes" into the search bar and press enter it queries the lens for q=taxes. I will keep an eye for this error tho.

**Comment by brendano** [comment]
here's my replication order

<img width="711" alt="screen shot 2016-02-28 at 6 30 36 pm" src="https://cloud.githubusercontent.com/assets/1677/13382711/728b49ae-de49-11e5-8926-13e1313adadc.png">
<img width="708" alt="screen shot 2016-02-28 at 6 30 47 pm" src="https://cloud.githubusercontent.com/assets/1677/13382713/728d6932-de49-11e5-9d5f-49676ee2d9c2.png">
<img width="728" alt="screen shot 2016-02-28 at 6 30 53 pm" src="https://cloud.githubusercontent.com/assets/1677/13382712/728c1348-de49-11e5-8c1c-e2e82decd204.png">

**Comment by AbeHandler** [comment]
ah ok. i think i know why that is happening and how to fix it quickly. thanks!

**Comment by AbeHandler** [comment]
I think this is fixed.

**Comment by brendano** [comment]
works for me
