### ISSUE TITLE
y-axis numbering cluttered if counts are high

### ISSUE THREAD

**Issue by brendano** [AbeHandler/rookie#157]
needs an algorithm to figure out a sensible spacing.

<img width="432" alt="screen shot 2016-02-28 at 7 54 41 pm" src="https://cloud.githubusercontent.com/assets/1677/13383267/2065ff78-de55-11e5-9527-8892a0b85d9c.png">

this is annoying. i never figured out what's a good algorithm that does a decent job at preserving human readability.

maybe

```
for each ticksize in [1,2,5,10, 20,50,100, (up to max y of the timeseries)]:
  check on the number of pixels that one tick would be equivalent to
choose the smallest tick size which has pixelsize > MINPIXELS
```

for MINPIXELS = 15, perhaps?

**Comment by brendano** [comment]
same as #151 though i dont think corpus size is the right determinant of ytick size.  it's query dependent.  the max y value being graphed is the right thing to use to determine (i.e. the y scale range)

**Comment by AbeHandler** [comment]
Forgot that d3 has a scale.ticks() function. I tried using d3 and it seems to fix it.

**Comment by AbeHandler** [comment]
sometimes the numbers on y axis seem too crowded. maybe just change font size. i think d3 does that.

**Comment by AbeHandler** [comment]
fixed
