### ISSUE TITLE
handle tick marks on resizing

### ISSUE THREAD

**Issue by AbeHandler** [AbeHandler/rookie#159]
there is no logic that handles window resizing. The width of UI.jsx is fixed as a prop (via main.js) based on the size of the window on load. 

will help with point 1 in #153

**Comment by AbeHandler** [comment]
you can resize now

**Comment by brendano** [comment]
pretty minor issue:  resizing doesnt work well with axes ticks.
this feels painful to fix, feel free to ignore

<img width="376" alt="screen shot 2016-02-29 at 6 09 01 pm" src="https://cloud.githubusercontent.com/assets/1677/13412200/9432f1bc-df0f-11e5-9cc4-1fd8f39a1067.png">

**Comment by AbeHandler** [comment]
fixed now
