### ISSUE TITLE
underlining and clicking

### ISSUE THREAD

**Issue by AbeHandler** [AbeHandler/rookie#182]
@myersnews "top of timeline: Found 388 stories for mitch landrieu” - “stories is underlined. is that meant to tell me it’s cilckable? why are you drawing attention to it?
similar vein: below timeline it says “showing 59 documents” - why documents? are they different from stories? if not, use the same word."

**Comment by AbeHandler** [comment]
hrm. I think I thought you should be able to get to the documents returned by the search engine if you wanted to. But then never finished. There are two fixes: 

1. remove the underline and have the status line read "analyzing Y total documents for X" (I like this one)
2. keep the underline, change stories to "documents" for consistency and have it show results for the entire timespan on click. 

 I think #1 is better. If you REALLY want to see the raw search engine results, you can slide the bars across the entire timespan -- but that is not really what Rookie is for.

**Comment by AbeHandler** [comment]
ah. i realized what this is. stories should be clickable in into facets/initial mode. so you can always be like: forget this rookie stuff i just want a search engine. once you are in summarization/documents mode (no sparklines) that underline should go away because it is confusing.

**Comment by brendano** [comment]
i think i'd have to see this one to have useful comments about it
