### ISSUE TITLE
empty documents

### ISSUE THREAD

**Issue by AbeHandler** [AbeHandler/rookie#185]
i clicked on the timeline at some point in 2010 and it says “summary of 0 docuemnts from Dec 31, 1969 to Dec. 31, 1969.” not sure what’s up there.

**Comment by brendano** [comment]
just saw this too.  timestamp=0 corresponds to 1/1/1970 so 12/31/1969 is maybe a 0 or -1 dummy value

**Comment by AbeHandler** [comment]
this is related to #182. As far as I can tell, the way to replicate error for #185 is to click stories on document load.

**Comment by AbeHandler** [comment]
Fixed w/

if you mouse up and there is no date range selected (i.e. you have not seen the grey rect yet) then it automatically selects a 2 month range centered at your click location. (2 months b/c less than 2 months and it is hard to tell what the black bars mean b/c overlap).
