### ISSUE TITLE
have an intro screen

### ISSUE THREAD

**Issue by AbeHandler** [AbeHandler/rookie#195]
this is as close as we come. need a basic rookie loading screen w/query bar

http://hobbes.cs.umass.edu:5000/?corpus=lens

**Comment by brendano** [comment]
wishlist: a view with a null Q/F/T that has all docs in the corpus selected (conceptually speaking).  shows timeseries of total number of docs per timestep (in a grayish neutral color), and text saying the total number of docs in the corpus, in the same place where it says "15 docs selected matching Q" ... e.g. "There are 11,435 total documents in the Rookie corpus".

Then below the timeseries graph, maybe some introductory text / graphic explaining what The Lens and/or Rookie is.  There are questions how deep into corpus-specific customization to get, but something simple might be reasonable.

**Comment by AbeHandler** [comment]
http://hobbes.cs.umass.edu:5000/intro?corpus=lens

**Comment by brendano** [comment]
nice!
