### ISSUE TITLE
timeseries is too tall?

### ISSUE THREAD

**Issue by AbeHandler** [AbeHandler/rookie#200]
Timeseries takes up too much screen real estate. It is used to help make sense of rookie + convey that this is not a traditional search engine. No reason it needs to be quite so big. 

On the other hand, too many facets will be overwhelming. It is good to show a few and then give ppl the option to see more.

**Comment by brendano** [comment]
i'm thinking more about when the sentence summaries are shown.  it feels a little misbalanced?  too big graph then?  OTOH if we're dedicated to the vertical split layout there may not be many other possibilities here.

i think the current number of facets is reasonable.

**Comment by AbeHandler** [comment]
Hrm. Once we show the sentences it is **definitely** better have the time series be smaller. the only possible disadvantage is that i feel like, in general, things in the UI should not move. So it will be a little disorienting if the timeseries jumps. 

Make a smaller timeseries, keep the number of facets and have a little more whitespace on the intro screen?

**Comment by brendano** [comment]
> Make a smaller timeseries, keep the number of facets and have a little more whitespace on the intro screen?

sure, sounds reasonable.
