### ISSUE TITLE
verbiage?

### ISSUE THREAD

**Issue by brendano** [AbeHandler/rookie#203]
NOW:
Found 32 documents for application formX and maintenance staffX

BETTER?:
Found 32 documents for application formX.  3 of them also contain maintenance staffX

**Comment by brendano** [comment]
<img width="1071" alt="screen shot 2016-04-11 at 5 18 24 pm" src="https://cloud.githubusercontent.com/assets/1677/14442757/7d2637ac-0009-11e6-84e1-9cc3c3bdb3ce.png">

**Comment by AbeHandler** [comment]
i think this is better. will update the js on hobbes after the user study tomorrow.

**Comment by AbeHandler** [comment]
hrm. slightly more complex. this starts to duplicate the verbiage from the bottom status. why are there two statuses? I think this is a vestige of older designs.

<img width="1262" alt="screen shot 2016-04-14 at 11 05 44 pm" src="https://cloud.githubusercontent.com/assets/1252925/14550303/77f327d4-0295-11e6-91b9-1028420c6dcf.png">
