### ISSUE TITLE
Document displayer? (Free text to html? research problem?)

### ISSUE THREAD

**Issue by AbeHandler** [AbeHandler/rookie#210]
One hinderance to new corpora (or even gawker) is that Rookie needs to link to original URLs. (dont have for gawker). If Rookie hosted the documents then we need to break paragraphs etc for display which is non trivial. Just going from, say, goose output to pretty HTML for display is a worthy standalone problem. Basically: where put the paragraph breaks, right?

**Comment by brendano** [comment]
actually gawker ones can be reconstructed with the numeric id in `all.meta`.  e.g. `gawker/5487177` => http://gawker.com/5487177

**Comment by brendano** [comment]
if there's a corpus without paragraph breaks -- the gawker extraction currently like this, though we could try doing a new extraction to be better about it -- a reasonable way to display is to just add a `<br>` after every sentence.  assuming sentence segmentation  i guess the other way is all sentences in one big paragraph.  i think that's harder to do.
