### ISSUE TITLE
make Q and F clickable in chart title

### ISSUE THREAD

**Issue by AbeHandler** [AbeHandler/rookie#214]
Q and F should be clickable in summary title bar

<img width="1273" alt="screen shot 2016-04-18 at 8 57 33 pm" src="https://cloud.githubusercontent.com/assets/1252925/14624375/32fc3a92-05a8-11e6-828c-7838b8f74c68.png">

**Comment by AbeHandler** [comment]
Clicking F should promote it to Q. But what should clicking Q do?

**Comment by brendano** [comment]
> Clicking F should promote it to Q. But what should clicking Q do?
>

delete F?

**Comment by AbeHandler** [comment]
delete F + reset UI to initial query settings? aka "requery" q.

**Comment by brendano** [comment]
yeah
