### ISSUE TITLE
show docs?

### ISSUE THREAD

**Issue by AbeHandler** [AbeHandler/rookie#221]
<img width="608" alt="screen shot 2016-07-22 at 9 57 19 am" src="https://cloud.githubusercontent.com/assets/1252925/17059350/bb7ed034-4ff2-11e6-9219-6a7de33f7811.png">

this is legacy rookie stuff. not showing the doclist makes the user study easier. just remove the link?

**Comment by brendano** [comment]
when i click on it things break anyway... i cant remember what this used to do ... hide the facet list to devote all space to docs/summaries?  i think something like the current layout is pretty good
