### ISSUE TITLE
scaling

### ISSUE THREAD

**Issue by brendano** [AbeHandler/rookie#223]
![screen shot 2016-07-22 at 2 49 03 pm](https://cloud.githubusercontent.com/assets/1677/17067811/8c6dab7a-501b-11e6-980c-a52a285379a5.png)

**Comment by AbeHandler** [comment]
scaling issue. not bug. good argument for rethinking the scale (not saying we necessarily need to worry about it, at least in the next month)

<img width="401" alt="screen shot 2016-07-26 at 10 28 30 am" src="https://cloud.githubusercontent.com/assets/1252925/17141834/c05914c6-531b-11e6-9907-cc11ac1a8f93.png">

**Comment by brendano** [comment]
the solutions we briefly discussed included
 - have gap b/w 0 and 1, then linear above 1
 - sqrt scaling
 - log scaling

**Comment by AbeHandler** [comment]
one comment, having tried out sqrt scaling.... Sqrt scaling squishes big counts more than small counts -- so small counts seem bigger on the overall Y scale. Advantage v. linear scaling: you can see small counts more easily. Disadvantage v. linear scaling: linear scaling tends to hide small counts, which gives a sort of visual smoothing effect. W/ linear scaling: it's easier to see "events" (bunches of big counts all together). This is probably turkable, altho perhaps not for this paper.

**Comment by brendano** [comment]
ah interesting.  yeah could try the whole "Tukey's ladder" of
transformations.  next paper or two away

**Comment by AbeHandler** [comment]
linear 

<img width="1279" alt="screenshot" src="https://cloud.githubusercontent.com/assets/1252925/17271372/cfef937c-5647-11e6-9647-53798ca9f14b.png">

sqrt

<img width="999" alt="screen shot 2016-07-30 at 11 22 08 am" src="https://cloud.githubusercontent.com/assets/1252925/17271375/e38290f6-5647-11e6-9dbe-7874af932b43.png">

**Comment by AbeHandler** [comment]
I actually think linear scale is better -- at least for Rookie newbies. it makes things more event-y. you know where to look. 8/3/16 user studies.
