### ISSUE TITLE
nav for more subjects area

### ISSUE THREAD

**Issue by myersnews** [AbeHandler/rookie#224]
when you click "more subjects" in the lower left area, it presumably goes down the list of related subjects. should that area have some kind of pagination or clue that you are essentially scrolling down a list? it's odd to use two buttons for nav.

**Comment by AbeHandler** [comment]
an old argument :) 

but yah, point taken. I think arrows + text in the middle will do it.

<img width="1069" alt="screen shot 2016-07-26 at 11 16 24 am" src="https://cloud.githubusercontent.com/assets/1252925/17143802/97f1564a-5322-11e6-8e37-ce18f5695bb0.png">

**Comment by brendano** [comment]
i agree arrows/pagination/something that seems directional would be good

**Comment by AbeHandler** [comment]
<img width="605" alt="screen shot 2016-07-27 at 4 31 46 pm" src="https://cloud.githubusercontent.com/assets/1252925/17191364/a83cbc74-5417-11e6-9106-4965484e7a9d.png">
