### ISSUE TITLE
design issues: global linguistic facet styling

### ISSUE THREAD

**Issue by brendano** [AbeHandler/rookie#58]
<img width="970" alt="screen shot 2015-12-30 at 11 22 09 pm" src="https://cloud.githubusercontent.com/assets/1677/12061117/2a9a46c6-af4c-11e5-965d-65c870885aea.png">
<img width="965" alt="screen shot 2015-12-30 at 11 22 02 pm" src="https://cloud.githubusercontent.com/assets/1677/12061118/2a9b4f76-af4c-11e5-9470-88b926bc3076.png">

this could use some tweaking. a few current issues

 - boldfacing turning on and off for the selection, is problematic because the width changes, bumping things on and off their line and changing their horizontal position more generally.
 - black on dark-gray is hard to read.  mouseover's even-darker-gray is harder to read.
 - wasteful of vertical space?
    - too much vertical padding within each button
    - too much whitespace between first and second lines
 - to think: should they look like buttons? or more like free text? should they be comma separated?  (i think something button-like is probably fine, but havent thought through the possibilities)

**Comment by AbeHandler** [comment]
@brendano minimum viable rookie fixes (1) wasted vertical space (2) bold facing changing the width (3) grey text / grey background visibility. 

I think there are long-term design issues for the "global linguistic facets" that are worth think about so keeping this open and moving it to "maximumrookie" milestone.

**Comment by AbeHandler** [comment]
closing b/c no longer relevant w/ new design

<img width="1071" alt="screen shot 2016-02-15 at 11 31 04 pm" src="https://cloud.githubusercontent.com/assets/1252925/13067327/f22954c4-d43c-11e5-9652-90232fe704b1.png">
![Uploading Screen Shot 2016-02-15 at 11.31.26 PM.png…]()
![Uploading Screen Shot 2016-02-15 at 11.31.35 PM.png…]()
![Uploading Screen Shot 2016-02-15 at 11.35.04 PM.png…]()

**Comment by AbeHandler** [comment]
<img width="1078" alt="screen shot 2016-02-15 at 11 31 35 pm" src="https://cloud.githubusercontent.com/assets/1252925/13067335/ff05646c-d43c-11e5-9630-cd61d97723d8.png">
