### ISSUE TITLE
get the search button working

### ISSUE THREAD

**Issue by AbeHandler** [AbeHandler/rookie#94]
this got lost in transition to react

**Comment by brendano** [comment]
probably minimumviable :)

**Comment by AbeHandler** [comment]
indeed!

**Comment by AbeHandler** [comment]
filler text in search bar should be normal & equal to q, not ghosted & equal to Q.

**Comment by AbeHandler** [comment]
changed this to react from foundation and broken again... !

**Comment by AbeHandler** [comment]
ok query bar is now part of the react ui
